### ISSUE TITLE
Test Run Questions and Issues

### ISSUE THREAD

**Issue by EMCP** [JRGEMCP/MAHRIO-STUDENT#2]
It's unclear, when you create a brand new user.. is this new user a Instructor by default?

Thinking by default it should be a student, no?  The tutorial creation pages seem to be in the student single page app by mistake?   Since the code is in this repo, I will add the issues I am having with it here.

**Create Account /dashboard/my-tutorials** 

Header styles look different, is this on purpose or should it be fixed?
Header will need to show the current logged in status
Should the first thing be creation of a tutorial?  Or selecting if you are a student vs teacher?

This page seems unnecessary, since it is just a button to start a new tutorial.. On new accounts what should be going here instead?  We should instead be pushing users into courses.. So perhaps directing them to lists of the hot courses?

Need place to create articles, not just tutorials

**Comment by EMCP** [comment]
Suggested data aspects for articles

  |   |   |  
-- | -- | -- | --
How are articles structured? | Related articles (AI) |   |  
  | author(s) | No assistants | No sylabus
  | Pay wall not enforced | Keyword tags |  

suggested data aspects for tutorials

  |   |   |  
-- | -- | -- | --
How are courses structured? | Length of time | Difficulty level | prerequisities
  | author(s) | assistants | sylabus
  | Pay wall enforced | Keyword tags |  
Course + User related metadata | Students progress | graduation | Pre-reqs (payment)
  |   |   |  
  | Ace editor for code |   |  


**Creating course /dashboard/my-tutorials/new**

Header styles look different, is this on purpose or should it be fixed?
Header will need to show the current logged in status?

I see a milestone panel, should this also be on the `/my-tutorials` page from earlier in the flow?
Milestone links point to `undefined` where should these be linking to?

Should teachers be allowed to control the URL this much?  Seems we should make a suggestion built from their title instead.. 
	
	For example `“Clustering Audio Data with Machine Learning”` becomes

 			`“clustering-audio-data-with-machine-learning”` as the URL 

It seems I can create a course but nothing inside of it.

**Comment by EMCP** [comment]
`/tutorials`

* Deployed tag is not a good tag, should just show all live courses when 0 filters applied
* I see filter by keyword, it should just say “search” in the search bar. Filters are different
* I see a star with the word tutorials in grey, guessing articles will have different logo?
It’s clickable.. Is this a favorites feature?
* I cannot remove the “Deployed” filter as of now
Search bar isn’t wired up

Filters style question
Should domains be vertical instead of horizontal?

**Comment by JesusGuerrero** [comment]
Lot's of things going on here...let's discuss this tomorrow (or asap)

**Comment by JesusGuerrero** [comment]
i've fixed the favorites feature. The page i've been working on is the consumer side (MAHRIO-A). You can be a student acting as a consumer and the favorites is attached to track your favorited tutorials. The filtering has been temporarily disabled due to a lot of work ahead to get it up to speed.

**Comment by EMCP** [comment]
Agreed, lots to review.  Understood some features are in progress.. just testing and laying out how I am finding things.  Happy to do another run this weekend, possibly try to automate as well.

**Comment by EMCP** [comment]
closing since Jesus changed the SPA setup and we need to review again from the beginning
